services:

  postgres:
    build: ./services/postgres
    image: dwh-postgres:16-tds
    container_name: dwh-postgres

    environment:
      POSTGRES_DB: dwh
      POSTGRES_USER: dwh
      POSTGRES_PASSWORD: dwh

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    restart: unless-stopped


  metabase:
    image: metabase/metabase:latest
    container_name: dwh-metabase

    ports:
      - "3000:3000"

    volumes:
      - metabase_data:/metabase-data

    restart: unless-stopped

    depends_on:
      - postgres


volumes:
  postgres_data:
  metabase_data:
