INSERT INTO bronze.clients (
    source_id,
    clients_code,
    fio,
    cardslist_code,
    sozdano,
    phone,
    user_code,
    other,
    phonemob,
    adres,
    jobadr,
    email,
    dnr,
    yuradres,
    fadres,
    egrpou,
    bank,
    isfizlico,
    asite,
    direktor,
    kontakt,
    inn,
    nomer_svidetelstva,
    sumpokupok,
    sumbonus,
    clients_category_id,
    isimported,
    sumpokupok_imported,
    iswholesale,
    deposit,
    creditlimit,
    load_dt
)
SELECT
    1 AS source_id,
    clients_code,
    fio,
    cardslist_code,
    sozdano,
    phone,
    user_code,
    other,
    phonemob,
    adres,
    jobadr,
    email,
    dnr,
    yuradres,
    fadres,
    egrpou,
    bank,
    COALESCE(isfizlico, 0) = 1 AS isfizlico,
    asite,
    direktor,
    kontakt,
    inn,
    nomer_svidetelstva,
    sumpokupok,
    sumbonus,
    clients_category_id,
    COALESCE(isimported, 0) = 1 AS isimported,
    sumpokupok_imported,
    COALESCE(iswholesale, 0) = 1 AS iswholesale,
    deposit,
    creditlimit,
    now() AS load_dt
FROM mssql.clients;
