INSERT INTO bronze.postavschiki (
    source_id,
    postav_code,
    postav_name,
    yuradres,
    fadres,
    phone,
    egrpou,
    bank,
    isfizlico,
    email,
    asite,
    direktor,
    kontakt,
    other,
    inn,
    nomer_svidetelstva,
    credit_day,
    isinternal,
    isactive,
    load_dt
)
SELECT
    1 AS source_id,
    postav_code,
    postav_name,
    yuradres,
    fadres,
    phone,
    egrpou,
    bank,
    COALESCE(isfizlico, 0) = 1 AS isfizlico,
    email,
    asite,
    direktor,
    kontakt,
    other,
    inn,
    nomer_svidetelstva,
    credit_day,
    COALESCE(isinternal, 0) = 1 AS isinternal,
    COALESCE(isactive, 0) = 1 AS isactive,
    now() AS load_dt
FROM mssql.postavschiki;
