INSERT INTO bronze.prihod (
    source_id,
    prihod_code,
    prihoddate,
    prihoduser,
    prihodsumma,
    other,
    postav_code,
    type,
    postavsumma,
    tax_date,
    tax_number,
    prihodstate,
    postavnakladnumber,
    invent_code,
    currency,
    exchange,
    odate,
    load_dt
)
SELECT
    1 AS source_id,
    prihod_code,
    prihoddate,
    prihoduser,
    prihodsumma,
    other,
    postav_code,
    type,
    postavsumma,
    tax_date,
    tax_number,
    prihodstate,
    postavnakladnumber,
    invent_code,
    currency,
    exchange,
    odate,
    now() AS load_dt
FROM mssql.prihod;
