INSERT INTO bronze.prihod_naklad (
    source_id,
    prihod_naklad_code,
    prihod_code,
    pname,
    kol,
    cena,
    product_code,
    nacenka,
    group_code,
    cardnumberean,
    old_pname,
    article,
    edenicaizm,
    cenapost,
    sales_product_code,
    expiration_date,
    certificate_number,
    optcena,
    optnacenka,
    load_dt
)
SELECT
    1 AS source_id,
    prihod_naklad_code,
    prihod_code,
    pname,
    kol,
    cena,
    product_code,
    nacenka,
    group_code,
    cardnumberean,
    old_pname,
    article,
    edenicaizm,
    cenapost,
    sales_product_code,
    expiration_date,
    certificate_number,
    optcena,
    optnacenka,
    now() AS load_dt
FROM mssql.prihod_naklad;
