INSERT INTO bronze.product (
    source_id,
    product_code,
    pshortname,
    pname,
    edenicaizm,
    cena,
    nacenka,
    optcena,
    optnacenka,
    isskidka,
    group_code,
    kolvo,
    cardnumberean,
    cardnumber,
    isourcode,
    toprint,
    article,
    r1,
    r2,
    r3,
    ves,
    isupakovka,
    analog1,
    analog2,
    other,
    mincena,
    spdvcena,
    nz,
    proizvoditel,
    poshtuchno,
    kolvop,
    cenapost,
    isprodukciya,
    bezprih,
    tax_type,
    isfiscal,
    isdopprinter,
    isscales,
    isprinteretiketok,
    ismaterial,
    isinternetshop,
    isprogrscales,
    expiration_date,
    certificate_number,
    isuse_expiration_date,
    parent_product_code,
    disable,
    plu,
    custom_field_cb1,
    bcforsearch,
    expiration,
    other2,
    load_dt
)
SELECT
    1 AS source_id,
    product_code,
    pshortname,
    pname,
    edenicaizm,
    cena,
    nacenka,
    optcena,
    optnacenka,
    (isskidka = 1)              AS isskidka,
    group_code,
    kolvo,
    cardnumberean,
    cardnumber,
    (isourcode = 1)             AS isourcode,
    (toprint = 1)               AS toprint,
    article,
    r1,
    r2,
    r3,
    ves,
    (isupakovka = 1)            AS isupakovka,
    analog1,
    analog2,
    other,
    mincena,
    spdvcena,
    nz,
    proizvoditel,
    (poshtuchno = 1)            AS poshtuchno,
    kolvop,
    cenapost,
    (isprodukciya = 1)          AS isprodukciya,
    (bezprih = 1)               AS bezprih,
    tax_type,
    (isfiscal = 1)              AS isfiscal,
    (isdopprinter = 1)          AS isdopprinter,
    (isscales = 1)              AS isscales,
    (isprinteretiketok = 1)     AS isprinteretiketok,
    (ismaterial = 1)            AS ismaterial,
    (isinternetshop = 1)        AS isinternetshop,
    (isprogrscales = 1)         AS isprogrscales,
    expiration_date,
    certificate_number,
    (isuse_expiration_date = 1) AS isuse_expiration_date,
    parent_product_code,
    (disable = 1)               AS disable,
    plu,
    (custom_field_cb1 = 1)      AS custom_field_cb1,
    bcforsearch,
    expiration,
    other2,
    now() AS load_dt
FROM mssql.product;
