INSERT INTO bronze.sales_product (
    source_id,
    sales_product_code,
    pname,
    cena,
    isskidka,
    sales_code,
    product_code,
    colvo,
    edenicaizm,
    sumvsego,
    nacenka,
    poshtuchno,
    kolvop,
    tax_type,
    isfiscal,
    isdopprinter,
    cena2,
    isprinteretiketok,
    cardnumberean,
    returned,
    kolvo_before,
    uktzed,
    excisestamps,
    printed_fpo,
    load_dt
)
SELECT
    1 AS source_id,
    sales_product_code,
    pname,
    cena,
    (isskidka = 1),
    sales_code,
    product_code,
    colvo,
    edenicaizm,
    sumvsego,
    nacenka,
    (poshtuchno = 1),
    kolvop,
    tax_type,
    (isfiscal = 1),
    (isdopprinter = 1),
    cena2,
    (isprinteretiketok = 1),
    cardnumberean,
    returned,
    kolvo_before,
    uktzed,
    excisestamps,
    (printed_fpo = 1),
    now() AS load_dt
FROM mssql.sales_product;
