INSERT INTO bronze.sales (
    source_id,
    sales_code,
    dates,
    clients_code,
    perc,
    sumproduct,
    sumdiscount,
    cardlist_code,
    splacheno,
    users_id,
    other,
    timercard,
    printed,
    ispayed,
    avans,
    bezskidki,
    sumd,
    pdv20,
    bazapdv20,
    opltype,
    deleted,
    uobjects_code,
    ispolnitel_code,
    frombonus,
    perc_bonus,
    fromdeposit,
    date1,
    cashdesk_code,
    fguid,
    round10,
    loctaxnum,
    taxnum,
    ispartial_payment,
    isunderpayment,
    load_dt
)
SELECT
    1 AS source_id,
    sales_code,
    dates,
    clients_code,
    perc,
    sumproduct,
    sumdiscount,
    cardlist_code,
    splacheno,
    users_id,
    other,
    timercard,
    (printed = 1),
    (ispayed = 1),
    avans,
    (bezskidki = 1),
    sumd,
    pdv20,
    bazapdv20,
    opltype,
    (deleted = 1),
    uobjects_code,
    ispolnitel_code,
    frombonus,
    perc_bonus,
    fromdeposit,
    date1,
    cashdesk_code,
    fguid,
    round10,
    loctaxnum,
    taxnum,
    (ispartial_payment = 1),
    (isunderpayment = 1),
    now() AS load_dt
FROM mssql.sales;
