INSERT INTO bronze.users (
    source_id,
    users_code,
    name,
    pass,
    dnr,
    pol,
    priem,
    adres,
    pasport,
    contact,
    other,
    issales,
    isclient,
    isproduct,
    isprihod,
    ispostav,
    iscards,
    iscardtypes,
    isuser,
    iskassa,
    isreport,
    isparam,
    pzp,
    iskassa2,
    ispereocenka,
    isothersoft,
    ekkapass,
    ekkalogin,
    ekkarowid,
    issessions,
    iseditsavecancelprihod,
    isfilteronsales,
    israschetonvyemka,
    isdeleteprihod,
    isdelsales,
    is_itogo_on_sales,
    avatar,
    isactive,
    isprihod_zak,
    isinvent,
    iscenapost,
    isprintcheck,
    oklad,
    depositoperacion,
    isireport,
    ischangeindreport,
    iscurrencies,
    skipsalesaddconfirmation,
    iskolvooninvent,
    iscashdesk,
    isclientaddeditonsales,
    isnotfiscalmenu_report,
    isnotfiscalmenu_income,
    isoplfilter,
    iscashdeskfilteronsales,
    iskassa1,
    isreportsonforms,
    load_dt
)
SELECT
    1 AS source_id,
    users_code,
    name,
    pass,
    dnr,
    (pol = 1),
    priem,
    adres,
    pasport,
    contact,
    other,
    (issales = 1),
    (isclient = 1),
    (isproduct = 1),
    (isprihod = 1),
    (ispostav = 1),
    (iscards = 1),
    (iscardtypes = 1),
    (isuser = 1),
    (iskassa = 1),
    (isreport = 1),
    (isparam = 1),
    pzp,
    (iskassa2 = 1),
    (ispereocenka = 1),
    (isothersoft = 1),
    ekkapass,
    ekkalogin,
    ekkarowid,
    (issessions = 1),
    (iseditsavecancelprihod = 1),
    (isfilteronsales = 1),
    (israschetonvyemka = 1),
    (isdeleteprihod = 1),
    (isdelsales = 1),
    (is_itogo_on_sales = 1),
    avatar,
    (isactive = 1),
    (isprihod_zak = 1),
    (isinvent = 1),
    (iscenapost = 1),
    (isprintcheck = 1),
    oklad,
    (depositoperacion = 1),
    (isireport = 1),
    (ischangeindreport = 1),
    (iscurrencies = 1),
    (skipsalesaddconfirmation = 1),
    (iskolvooninvent = 1),
    (iscashdesk = 1),
    (isclientaddeditonsales = 1),
    (isnotfiscalmenu_report = 1),
    (isnotfiscalmenu_income = 1),
    (isoplfilter = 1),
    ("isCashDeskFilterOnSales" = 1),
    (iskassa1 = 1),
    (isreportsonforms = 1),
    now() AS load_dt
FROM mssql.users u;
