CREATE TABLE IF NOT EXISTS bronze.clients (
    source_id int NOT NULL,
    clients_code int NOT NULL,
    fio text NOT NULL,
    cardslist_code int NULL,
    sozdano timestamp NULL,
    phone text NULL,
    user_code int NOT NULL,
    other text NULL,
    phonemob text NULL,
    adres text NULL,
    jobadr text NULL,
    email text NULL,
    dnr timestamp NULL,
    yuradres text NULL,
    fadres text NULL,
    egrpou text NULL,
    bank text NULL,
    isfizlico boolean NULL,
    asite text NULL,
    direktor text NULL,
    kontakt text NULL,
    inn text NULL,
    nomer_svidetelstva text NULL,
    sumpokupok numeric(24,2) NOT NULL,
    sumbonus numeric(24,2) NOT NULL,
    clients_category_id int NOT NULL,
    isimported boolean NOT NULL,
    sumpokupok_imported numeric(24,2) NOT NULL,
    iswholesale boolean NOT NULL,
    deposit numeric(24,2) NOT NULL,
    creditlimit numeric(24,2) NOT NULL,
    load_dt timestamp NOT NULL
);
