CREATE TABLE IF NOT EXISTS bronze.product (
    source_id               int NOT NULL,
    product_code            int NOT NULL,
    pshortname              text NULL,
    pname                   text NOT NULL,
    edenicaizm              text NULL,
    cena                    numeric(24,2) NOT NULL,
    nacenka                 double precision NOT NULL,
    optcena                 numeric(24,2) NULL,
    optnacenka              double precision NOT NULL,
    isskidka                boolean NOT NULL,
    group_code              int NOT NULL,
    kolvo                   numeric(24,4) NULL,
    cardnumberean           text NOT NULL,
    cardnumber              bigint NULL,
    isourcode               boolean NOT NULL,
    toprint                 boolean NULL,
    article                 text NULL,
    r1                      int NULL,
    r2                      int NULL,
    r3                      int NULL,
    ves                     numeric(24,3) NULL,
    isupakovka              boolean NULL,
    analog1                 text NULL,
    analog2                 text NULL,
    other                   text NULL,
    mincena                 numeric(24,2) NULL,
    spdvcena                numeric(24,2) NULL,
    nz                      int NULL,
    proizvoditel            text NULL,
    poshtuchno              boolean NOT NULL,
    kolvop                  int NULL,
    cenapost                numeric(24,2) NULL,
    isprodukciya            boolean NOT NULL,
    bezprih                 boolean NOT NULL,
    tax_type                int NULL,
    isfiscal                boolean NOT NULL,
    isdopprinter            boolean NOT NULL,
    isscales                boolean NOT NULL,
    isprinteretiketok       boolean NOT NULL,
    ismaterial              boolean NOT NULL,
    isinternetshop          boolean NOT NULL,
    isprogrscales           boolean NOT NULL,
    expiration_date         timestamp NULL,
    certificate_number      text NULL,
    isuse_expiration_date   boolean NOT NULL,
    parent_product_code     int NULL,
    disable                 boolean NOT NULL,
    plu                     int NULL,
    custom_field_cb1        boolean NOT NULL,
    bcforsearch             text NOT NULL,
    expiration              int NULL,
    other2                  text NULL,
    load_dt                 timestamp NOT NULL
);
