CREATE TABLE IF NOT EXISTS bronze.sales_product (
    source_id int NOT NULL,
    sales_product_code int NOT NULL,
    pname text NOT NULL,
    cena numeric(24,2) NOT NULL,
    isskidka boolean NOT NULL,
    sales_code int NULL,
    product_code int NOT NULL,
    colvo numeric(24,4) NOT NULL,
    edenicaizm text NULL,
    sumvsego numeric(24,2) NOT NULL,
    nacenka double precision NOT NULL,
    poshtuchno boolean NOT NULL,
    kolvop int NULL,
    tax_type int NULL,
    isfiscal boolean NOT NULL,
    isdopprinter boolean NOT NULL,
    cena2 numeric(24,2) NULL,
    isprinteretiketok boolean NOT NULL,
    cardnumberean text NULL,
    returned numeric(24,4) NULL,
    kolvo_before numeric(24,4) NULL,
    uktzed text NULL,
    excisestamps text NOT NULL,
    printed_fpo boolean NOT NULL,
    load_dt timestamp NOT NULL
);
