CREATE TABLE IF NOT EXISTS bronze.sales (
    source_id int NOT NULL,
    sales_code int NOT NULL,
    dates timestamp NOT NULL,
    clients_code int NOT NULL,
    perc double precision NOT NULL,
    sumproduct numeric(24,2) NOT NULL,
    sumdiscount numeric(24,2) NOT NULL,
    cardlist_code int NULL,
    splacheno numeric(24,2) NULL,
    users_id int NOT NULL,
    other text NULL,
    timercard int NULL,
    printed boolean NOT NULL,
    ispayed boolean NOT NULL,
    avans numeric(24,2) NOT NULL,
    bezskidki boolean NOT NULL,
    sumd numeric(24,2) NOT NULL,
    pdv20 numeric(24,2) NULL,
    bazapdv20 numeric(24,2) NULL,
    opltype int NOT NULL,
    deleted boolean NOT NULL,
    uobjects_code int NOT NULL,
    ispolnitel_code int NOT NULL,
    frombonus numeric(24,2) NULL,
    perc_bonus double precision NOT NULL,
    fromdeposit numeric(24,2) NULL,
    date1 timestamp NULL,
    cashdesk_code int NOT NULL,
    fguid text NULL,
    round10 numeric(24,2) NOT NULL,
    loctaxnum int NULL,
    taxnum text NULL,
    ispartial_payment boolean NOT NULL,
    isunderpayment boolean NOT NULL,
    load_dt timestamp NOT NULL
);
