CREATE TABLE IF NOT EXISTS bronze.users (
    source_id int NOT NULL,
    users_code int NOT NULL,
    name text NOT NULL,
    pass text NOT NULL,
    dnr timestamp NULL,
    pol boolean NULL,
    priem timestamp NULL,
    adres text NULL,
    pasport text NULL,
    contact text NULL,
    other text NULL,
    issales boolean NOT NULL,
    isclient boolean NOT NULL,
    isproduct boolean NOT NULL,
    isprihod boolean NOT NULL,
    ispostav boolean NOT NULL,
    iscards boolean NOT NULL,
    iscardtypes boolean NOT NULL,
    isuser boolean NOT NULL,
    iskassa boolean NOT NULL,
    isreport boolean NOT NULL,
    isparam boolean NULL,
    pzp double precision NULL,
    iskassa2 boolean NOT NULL,
    ispereocenka boolean NOT NULL,
    isothersoft boolean NOT NULL,
    ekkapass text NULL,
    ekkalogin text NULL,
    ekkarowid int NULL,
    issessions boolean NOT NULL,
    iseditsavecancelprihod boolean NOT NULL,
    isfilteronsales boolean NOT NULL,
    israschetonvyemka boolean NOT NULL,
    isdeleteprihod boolean NOT NULL,
    isdelsales boolean NOT NULL,
    is_itogo_on_sales boolean NOT NULL,
    avatar text NOT NULL,
    isactive boolean NOT NULL,
    isprihod_zak boolean NOT NULL,
    isinvent boolean NOT NULL,
    iscenapost boolean NOT NULL,
    isprintcheck boolean NOT NULL,
    oklad numeric(24,2) NULL,
    depositoperacion boolean NOT NULL,
    isireport boolean NOT NULL,
    ischangeindreport boolean NOT NULL,
    iscurrencies boolean NOT NULL,
    skipsalesaddconfirmation boolean NOT NULL,
    iskolvooninvent boolean NOT NULL,
    iscashdesk boolean NOT NULL,
    isclientaddeditonsales boolean NOT NULL,
    isnotfiscalmenu_report boolean NOT NULL,
    isnotfiscalmenu_income boolean NOT NULL,
    isoplfilter boolean NOT NULL,
    iscashdeskfilteronsales boolean NOT NULL,
    iskassa1 boolean NOT NULL,
    isreportsonforms boolean NOT NULL,
    load_dt timestamp NOT NULL
);
